server:
    port: 8081
spring:
    datasource:
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        properties:
            hibernate:
                format_sql: true
        show-sql: true

springdoc:
    api-docs:
        path: /api-docs